### ISSUE TITLE
LoRa_Gateway.py

### ISSUE THREAD

**Issue by SwiftFlying** [TomasTT7/LoRa_SSDV#1]
Hi,
I can't run the PY file. Can I send a EXE file to me?
Traceback (most recent call last):
  File "C:\Users\hp1\Desktop\OV5640\LoRa_Gateway.py", line 30, in <module>
    from Tkinter import *
ModuleNotFoundError: No module named 'Tkinter'

**Comment by PiroRiro** [comment]
Hello, i have the same problem. How can i solved it? I have add to pip Tkinter, but still get the error msg like from SwiftFlying.
